### ISSUE TITLE
Issue: Unable to install mmcv==2.0.0 (Python 3.10, PyTorch 2.4.1, CUDA 12.1)

### ISSUE THREAD

**Issue by irfanhassan527** [ZhaoxuLi123/SpecDETR#1]
Hello,
I'm trying to set up this repository, but I'm facing an issue with installing mmcv==2.0.0.

Environment:
Python: 3.10

PyTorch: 2.4.1

CUDA: 12.1

Problem:
When I try to install mmcv==2.0.0 using:
pip install mmcv==2.0.0

I get the following error:
OSError: CUDA_HOME environment variable is not set.

<img width="907" alt="Image" src="https://github.com/user-attachments/assets/44c1a6c0-9188-4a2c-9e14-00e86848f42e" />

Notes:
I can install older or the latest versions of mmcv without issues.

However, the repository seems to strictly require mmcv==2.0.0.

I tried setting CUDA_HOME but faced compatibility issues due to the PyTorch/CUDA version mismatch.

Request:
Can you please provide a working Dockerfile to set up the repository?
Or, can you please guide me on which compatible versions of:
Python, PyTorch, CUDA, and mmcv are used for this project.

Thanks in advance for your help!

**Comment by ZhaoxuLi123** [comment]
You can use `mmcv>=2.0.0` for this project. 


My configuration is as follows:
- Python: 3.7
- CUDA: 11.2
- PyTorch: 1.10
- mmcv: 2.0.0
For installation guidance, you can refer to the official installation instructions provided by MMDetection:
[https://mmdetection.readthedocs.io/en/latest/get_started.html](https://mmdetection.readthedocs.io/en/latest/get_started.html)

**Comment by irfanhassan527** [comment]
Hi @ZhaoxuLi123,

I wanted to thank you for your quick support and guidance. I was able to resolve the issue successfully with your help! 🙌

Your project is incredibly valuable, and I appreciate the time you take to support the community. Looking forward to exploring more of your work and contributing where I can.

Thanks again!

Best regards,
Irfan Hassan
